[package]
name = "gst-plugin-png"
version.workspace = true
authors = ["Natanael Mojica <neithanmo@gmail.com>"]
repository.workspace = true
license = "MIT OR Apache-2.0"
edition.workspace = true
rust-version.workspace = true
description = "GStreamer Rust PNG encoder/decoder"

[dependencies]
gst.workspace = true
gst-video.workspace = true
png = "0.17.2"
parking_lot = "0.12"

[dev-dependencies]
gst-check.workspace = true

[lib]
name = "gstrspng"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
static = []
capi = []
doc = ["gst/v1_18"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-video-1.0, gobject-2.0, glib-2.0, gmodule-2.0"

[package.metadata.gstreamer]
release_date = "2025-10-31"
